<#68> feat: 댓글(Comment) 수정/삭제 API 구현
J2KB-5th/chippo pull request #73
Opened 2021-12-22 16:19 UTC by dadahee

## 내용
- 댓글 등록/삭제 API 구현
- 조회 브랜치에서 분기하여, 등록/삭제 브랜치 -> 조회 브랜치로 PR 올립니다!

## 연관 이슈
- solve #69
- 설계: #7 
- 조회 API 구현: #68

2021-12-27 11:13 UTC, nrudev reviewed
많이 늦었죠? 죄송합니다! 면접 준비 때문에요... 오늘 막 끝나서 부랴부랴 리뷰 남깁니다. 죄송해요!

2021-12-27 11:13 UTC, nrudev commented on back-end/src/main/java/com/j2kb5th/chippo/comment/service/CommentServiceImpl.java
> +        commentRepository.delete(comment);
여기서 보니 참조변수 interview가 사용되는 곳이 없는 것 같은데, 참조변수를 적용해두신 이유가 있나요?

2021-12-27 11:13 UTC, nrudev commented on back-end/src/main/java/com/j2kb5th/chippo/comment/service/CommentServiceImpl.java
> +        commentRepository.delete(comment);
아 그리구 findInterviewById와 findByInterviewId 두 메서드명이 너무 비슷해서 조금 헷갈릴 것 같은데, 메서드명을 좀 정리해주실 수 있을까요?

2021-12-27 11:13 UTC, nrudev commented on back-end/src/main/java/com/j2kb5th/chippo/comment/service/CommentServiceImpl.java
> +        Comment comment = commentRequest.toEntity(user, interview);
제가 기억하기론 dto <-> entity 변환작업은 controller에서 하기로 했던 것 같은데, 이거는 특별하게 여기서 변환하는 이유를 알 수 있을까요?

2021-12-27 14:48 UTC, dadahee commented on back-end/src/main/java/com/j2kb5th/chippo/comment/service/CommentServiceImpl.java
> +        commentRepository.delete(comment);
기술면접 존재 여부는 검사해야 하기 때문입니다 :) 말씀해주신 메서드명은 `findCommentsByInterviewId`로 수정할게요.

2021-12-27 14:49 UTC, dadahee commented on back-end/src/main/java/com/j2kb5th/chippo/comment/service/CommentServiceImpl.java
> +        Comment comment = commentRequest.toEntity(user, interview);
request dto -> entity이기 때문에 컨트롤러 변환에 해당하지 않습니다 :) 희승님께서는 해당 내용도 컨트롤러에서 작업 하셨나요?

2021-12-27 15:36 UTC, nrudev commented on back-end/src/main/java/com/j2kb5th/chippo/comment/service/CommentServiceImpl.java
> +        Comment comment = commentRequest.toEntity(user, interview);
아아 그렇네요. 확인했습니다!

2021-12-27 16:17 UTC, nrudev reviewed
제가 아무래도 머지 승인 순서를 잘못 했나 싶네요.
이걸 먼저 승인하고, 조회를 승인했어야 하는 거 같은데...

2021-12-27 16:26 UTC, nrudev requested changes
해당 커밋에 메서드명 변경 내역이 없는 것 같은데, 혹시 누락된 걸까요?

2021-12-28 08:06 UTC, dadahee commented
> 해당 커밋에 메서드명 변경 내역이 없는 것 같은데, 혹시 누락된 걸까요?

두 번째 커밋이 푸시에 반영이 안 되었네요 ㅎㅎ;

2021-12-28 08:11 UTC, merged